### ISSUE TITLE
Playing Cards during combat

### ISSUE THREAD

**Issue by gutterkid13** [RhombusWeasel/Deadlands-Classic#3]
Hi,

I tried this System and I am curious, when we start combat and use cards, sometimes the cards are not deleted from the player sheet. I tried to find in code:
```

    _on_play_card(event) {
        event.preventDefault();
        let element = event.currentTarget;
        let itemId = element.closest(".item").dataset.itemid;
        let item = this.actor.getOwnedItem(itemId);
        ChatMessage.create({ content: `Playing ${item.name}`});
        game.socket.emit("system.deadlands_classic", {
            operation: 'discard_card',
            data: {
                name: item.name,
                type: item.type
            }
        });
        return this.actor.deleteOwnedItem(item._id);
    }

```

I think this line:
`return this.actor.deleteOwnedItem(item._id);
`

should be changed to:
`return this.actor.deleteOwnedItem(itemId);`

Thanks in advance.

Best regards,
Gutterkid

**Comment by RhombusWeasel** [comment]
Hi, thanks for the bug report.
You are correct, that should be itemId.  I've pushed an update if you'd like to test but I fear that the issue might not be this.
Do the cards get removed at the end of the combat?  I'll leave this open a while to continue testing.

**Comment by gutterkid13** [comment]
Unfortunately it is not the whole solution. The cards are still not deleted sometimes.
Although they are not deleted after combat.

Thanks for your quick reply.

**Comment by RhombusWeasel** [comment]
Yes, I've been testing.  It seems that they can remain from any of the actions you can use them for.  I'll take a look into this today.

Thanks for using the system, I figured it'd just be me using it really.  If you have any other issues, let me know so I can fix it for my own games. 👍

**Comment by gutterkid13** [comment]
Thanks for your work.

Maybe you can explain me this:
```
game.socket.emit("system.deadlands_classic", {
            operation: "discard_card",
            data: {
                name: item.name,
                type: item.type
            }
```

Does this point to the deck.js:

```
    discard_card: function(data) {
        if (game.user.isGM) {
            if (data.name == "Joker (Black)") {
                ChatMessage.create({ content: `
                    Black Joker!
                    You lose your next highest card, the combat deck will be reshuffled at the end of the round 
                    and the Marshal draws a Fate Chip.`
                });
                game.dc.combat_shuffle = true
            }
            game.dc.action_discard.push(data)
        }
    },
```
???
Because in this case, this discard_card should only work, when the user is GM or has GM Assistant right. The Black Joker stuff should happen for users who are not for GM (==false missing).

**Comment by RhombusWeasel** [comment]
Yes, the GM player stores the action deck locally and sends cards to players that request them.
In the case of the Black Joker stuff the GM player will send out a chat message to all players with the text telling them what happens and sets the flag to shuffle the discard pile into the deck at the start of the next round then puts the joker into the discard pile.
The socket event is picked up by all players you see so only the GM player needs to do anything.

**Comment by gutterkid13** [comment]
Ok, I think I understand. :) Thanks a lot.

Some more questions. Normally the GM should be also possible to draw cards depending on how many NPCs and their quickness results. At the moment this is missing or?

And would it be ok for you, if I add translation to German?

**Comment by RhombusWeasel** [comment]
Yes, that was going to be the next thing I add to the Marshal sheet.  I'll try to get that in this weekend, I also want to add a bunch of checkboxes to calculate the TN for combat.
For the translation, that'd be great!, based on your responses here I'm guessing you know how to do that, if you need any help let me know.

**Comment by RhombusWeasel** [comment]
Think I've got it.  changed each call to delete the item and then return a fresh call of getData() which should clear the list.
Update pushed.
If you could test as well and let me know.

**Comment by gutterkid13** [comment]
Hi Rhombus,

I updated Deadlands-classic to the newest Version within Foundry and created a new "Game World". Now it does not draw any cards.
![Bildschirmfoto 2020-12-31 um 20 14 54](https://user-images.githubusercontent.com/76665791/103423070-fca00f80-4ba4-11eb-87c4-948a4141ac96.png)

When I just updated the game system and tried in an already existing Deadlands-Game-World. It worked like before, some cards have been deleted. Some not.

**Comment by RhombusWeasel** [comment]
Could you just clarify for me, you created an new game world, then you created 2 actors Klaus and a gm sheet. Then did you setup another player and login with that player to test?
Cards are sent to the actor controlled by the requesting player so the GM can't draw for players even if he's set to be that player in the config setting apparently, I just checked.

**Comment by gutterkid13** [comment]
Ah, I See the problem was the actor was not linked to the user at this moment.

So that's why console did not find an actor. Sorry, for the confusion. For me it looks very good now. Thanks!

We will have a session on saturday. 👍

**Comment by RhombusWeasel** [comment]
Good luck with your session man, if you or your players have any feature requests just let me know.
